### Match Winner Predictor

##### Problem Statement:
The goal of this model is to predict the winner of an IPL match based on match conditions such as teams, toss decision, venue, and historical team performance.

##### Target Variable:
`winner` 

We convert the winner into a binary outcome:
Team1 wins → 1
Team2 wins → 0
Features:

##### Features:
From matches dataset:
* toss_winner
* toss_decision
* venue
* team1
* team2
* season

Engineered features:
* team1_win_rate
* team2_win_rate
* team1_avg_score
* team2_avg_score

##### Model Type:
Classification

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
matches = pd.read_csv("../data/matches.csv")
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [3]:
deliveries = pd.read_csv("../data/deliveries.csv")
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [4]:
matches = matches[matches["winner"].notna()]

In [5]:
matches["team1_win"] = np.where(
    matches["winner"] == matches["team1"], 1, 0
)

In [6]:
features = [
    "team1",
    "team2",
    "toss_winner",
    "toss_decision",
    "venue",
    "season"
]

X = matches[features]

y = matches["team1_win"]

In [7]:
#encode categorical variables
X = pd.get_dummies(X)

In [14]:
import joblib
joblib.dump(X.columns.tolist(), "../models/match_columns.pkl")

['../models/match_columns.pkl']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

Model 1 — Logistic Regression

In [9]:
log_model = LogisticRegression(max_iter=200)

log_model.fit(X_train, y_train)
pred_log = log_model.predict(X_test)

In [10]:
print("Accuracy:", accuracy_score(y_test, pred_log))

Accuracy: 0.536697247706422

Model 2 — Random Forest Classifier

In [11]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)
pred_rf = rf.predict(X_test)

In [12]:
print("Accuracy:", accuracy_score(y_test, pred_rf))

Accuracy: 0.5137614678899083

In [13]:
import joblib

joblib.dump(rf, "../models/match_winner_model.pkl")

['../models/match_winner_model.pkl']